"""Specialize the OCaml oracle matrix to avoid a large runtime AST dispatcher."""
from pathlib import Path

root = Path(__file__).resolve().parent.parent
formulas = ['diffP', 'temporalAlways Nat diffP', 'temporalEventually Nat diffP',
    'temporalAlways Nat (temporalEventually Nat diffP)',
    'temporalEventually Nat (temporalAlways Nat diffP)', 'leadsTo Nat diffQ diffP',
    'temporalNext Nat diffP', 'stable Nat diffP', 'temporalLater Nat diffP',
    'temporalNot Nat (temporalAlways Nat diffP)']
behaviors = ['lasso Nat (listNil Nat) 1 (listNil Nat)',
    'lasso Nat (listNil Nat) 0 (listNil Nat)',
    'lasso Nat (listNil Nat) 1 (listCons Nat 0 (listNil Nat))',
    'lasso Nat (listCons Nat 0 (listNil Nat)) 1 (listNil Nat)',
    'stream Nat (fun (s : Stage) => 1)', 'stream Nat (fun (s : Stage) => 0)',
    'stream Nat (fun (s : Stage) => boolNat (listFold One Bool s true (fun (v : Bool) (u : One) => boolNot v)))']
lines = ['-- Generated by scripts/differential.py from the oracle matrix.',
    'def diffFuel : Fuel := listCons One one (listCons One one (listCons One one (listCons One one (listNil One))))',
    'def diffVerdict : Verdict -> Nat := fun (v : Verdict) => match v as self in Verdict return Nat with',
    '  | verdictFalse => 0 | verdictUnknown => 1 | verdictTrue => 2']
for fi, formula in enumerate(formulas):
    for bi, behavior in enumerate(behaviors):
        for part, result_type, convert in [('Holds', 'Verdict', 'diffVerdict'), ('Depth', 'OmegaValue', 'diffDepth')]:
            lines += [f'def diffTemporal{part}_{fi}_{bi} : Nat :=',
                f'  match (temporal{part} Nat diffFuel ({formula}) ({behavior})) as r in Result return Nat with',
                f'  | failure e => 999 | success v => {convert} v']
(root / 'test/differential_temporal.kan').write_text('\n'.join(lines)+'\n')
