"""Generate closed UTF-8 and decimal-power values for Kanon's core syntax."""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VALUES = {
    'textCh': 'ch', 'textSlash': '/', 'textContext': ' > ',
    'textComma': ',', 'textSemi': ';', 'textArrow': '->', 'textMapsTo': '|->',
    'textOpenSet': '{', 'textCloseSet': '}', 'textOpenGraph': '[', 'textCloseGraph': ']',
    'textPink': 'pink(', 'textBlue': 'blue(', 'textPair': 'pair(', 'textCloseParen': ')',
    'textTrue': 'ttrue', 'textFalse': 'ffalse', 'textTuple': 'tuple[', 'textMinus': '-',
    'textNotComposable': ': not composable (tgt ', 'textNeqSrc': ' <> src ',
    'textNoArrow': ': no arrow ', 'textSpaceArrow': ' -> ', 'textNoSuch': 'no such ',
    'textColon': ': ', 'textOutside': ' outside domain', 'textUniversal': 'universal property failed: ',
    'textIsNotMonic': ' is not monic', 'textEmptySet': ': empty set',
    'textNotSingleton': ': expected a singleton, got ', 'textClash': 'clash: ', 'textVersus': ' vs ',
    'textCyclic': 'cyclic: ', 'textOccurs': ' occurs in ', 'textIrreducible': ': no non-trivial decomposition',
    'textNoWitness': 'no witness with a common leading operator',
    'textBudget': ': budget exhausted after ', 'textSteps': ' steps',
    'textUnbound': 'unbound ', 'textIn': ' in ', 'textIllFormed': ': ill-formed (', 'textUnsupported': ': unsupported (',
    'textFinSet': 'FinSet', 'textFinsetApp': 'Finset.app', 'textFinsetCompose': 'Finset.comp',
    'textNotParallel': 'the two arrows are not a parallel pair',
    'textCoequalizer': 'Finset.set_coequalizer', 'textEqualizer': 'Finset.set_equalizer',
    'textEngine': 'Colimit_engine.colimit', 'textNode': 'node', 'textEdge': 'edge',
    'textLanLocate': 'Lan.locate', 'textCommaAbsent': 'comma object absent',
    'textIteratedCoproduct': 'iterated_coproduct', 'textFixedPoint': 'fixed_point', 'textWColimit': 'w_colimit',
    'textVar': 'var(', 'textOpenParen': '(', 'textFinKleisli': 'FinKleisli', 'textSubArrow': '=>',
    'textUnifyDomain': 'a term mentions a variable outside the substitution target',
    'textFkUniversal': 'FinKleisli.coequalizer (universal part)',
    'textFkUniversalOmitted': 'the source library computes the most general unifier and omits the universal part',
    'textLaterGuard': 'Later.fix: step is not later-guarded',
    'textRule': 'Rule', 'textRuleShape': 'premise shape does not match the rule',
    'textRuleSpec': 'facts have different specs', 'textRuleObligation': 'rule obligation failed',
    'textArrowCategory': 'ArrowCat', 'textFinGraph': 'FinGraph',
    'textDecimalRange': '[Nat outside decimal rendering range]',
}


def nat_list(values):
    result = '(listNil Nat)'
    for value in reversed(values):
        result = f'(listCons Nat {value} {result})'
    return result


lines = ['-- Generated by scripts/literals.py. UTF-8 bytes, without runtime host policy.']
for name, value in VALUES.items():
    lines.append(f'def {name} : Text := {nat_list(value.encode())}')
lines.append(f'def decimalPowers : List Nat := {nat_list([10 ** n for n in range(18, -1, -1)])}')
lines.append(f'def decimalNine : List Nat := {nat_list(list(range(9)))}')
(ROOT / 'src' / 'literals.kan').write_text('\n'.join(lines) + '\n')
