"""Generate the thin smart-constructor layer from the closed Temporal schema."""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCHEMA = [
    ('True', []), ('False', []), ('State', [('name', 'Text'), ('pred', 'A -> Bool')]),
    ('Action', [('name', 'Text'), ('pred', 'A -> A -> Bool')]),
    ('And', [('left', 'Temporal A'), ('right', 'Temporal A')]),
    ('Or', [('left', 'Temporal A'), ('right', 'Temporal A')]),
    ('Not', [('body', 'Temporal A')]),
    ('Implies', [('left', 'Temporal A'), ('right', 'Temporal A')]),
    *[(name, [('body', 'Temporal A')]) for name in ['Later', 'Next', 'Always', 'Eventually']],
]
lines = ['-- Generated by scripts/temporal_constructors.py.']
for name, fields in SCHEMA:
    signature = ' -> '.join([f'({ty})' for _, ty in fields] + ['Temporal A'])
    binders = ' '.join(f'({var} : {ty})' for var, ty in fields)
    values = ' '.join(var for var, _ in fields)
    lines.append(f'def temporal{name} : (0 A : Type 0) -> {signature} :=')
    lines.append(f'  fun (0 A : Type 0) {binders} => (tl{name} {values} : Temporal A)')
(ROOT / 'src' / 'temporal_constructors.kan').write_text('\n'.join(lines) + '\n')

lines = ['-- Generated exhaustive formula destructors.']
for wanted in ['Always', 'Eventually', 'Implies', 'And']:
    result_type = 'Temporal A' if wanted in ['Always', 'Eventually'] else 'prod (Temporal A, Temporal A)'
    lines.append(f'def as{wanted} : (0 A : Type 0) -> Temporal A -> Result ({result_type}) :=')
    lines.append('  fun (0 A : Type 0) (p : Temporal A) =>')
    lines.append(f'  match p as self in Temporal return Result ({result_type}) with')
    for name, fields in SCHEMA:
        pattern = ' '.join(var for var, _ in fields)
        value = 'body' if len(fields) == 1 else 'tuple (left, right)'
        result = f'ok ({result_type}) ({value})' if name == wanted else f'err ({result_type}) (illFormed textRule textRuleShape)'
        lines.append(f'  | tl{name} {pattern} => {result}')
(ROOT / 'src' / 'temporal_destructors.kan').write_text('\n'.join(lines) + '\n')
