"""Generate exhaustive closure comparison and annotated constructors."""
from pathlib import Path

root = Path(__file__).resolve().parent.parent
ctors = [
    ('closureOf', [('sentences', 'List S')], 'listEqual S eqS sentences sentences2'),
    ('closeUnion', [('left', 'Closure O H S'), ('right', 'Closure O H S')],
     'boolAnd (closureEqual O H S eqO eqH eqS left left2) (closureEqual O H S eqO eqH eqS right right2)'),
    ('closeTranslate', [('map', 'H'), ('body', 'Closure O H S')],
     'boolAnd (eqH map map2) (closureEqual O H S eqO eqH eqS body body2)'),
    ('inverseTranslate', [('map', 'H'), ('body', 'Closure O H S')],
     'boolAnd (eqH map map2) (closureEqual O H S eqO eqH eqS body body2)'),
    ('starOf', [('signature', 'O'), ('body', 'Closure O H S')],
     'boolAnd (eqO signature signature2) (closureEqual O H S eqO eqH eqS body body2)'),
]
types = '(0 O : Type 0) -> (0 H : Type 0) -> (0 S : Type 0) -> '
args = '(0 O : Type 0) (0 H : Type 0) (0 S : Type 0)'
lines = ['-- Generated by scripts/theory_constructors.py.', 'mu Closure (O : Type 0) (H : Type 0) (S : Type 0) : Type 0 :=']
for name, fields, _ in ctors:
    lines.append(f'| {name} ' + ' '.join(f'({n} : {t})' for n, t in fields) + ' : Closure O H S')
for name, fields, _ in ctors:
    lines += [f'def mk{name[0].upper()+name[1:]} : {types}' + ''.join(f'({t}) -> ' for _, t in fields) + 'Closure O H S :=',
              f'  fun {args} ' + ' '.join(f'({n} : {t})' for n, t in fields) + f' => {name} ' + ' '.join(n for n, _ in fields)]
lines += [f'def rec closureEqual : {types}(O -> O -> Bool) -> (H -> H -> Bool) -> (S -> S -> Bool) -> Closure O H S -> Closure O H S -> Bool :=',
          f'  fun {args} (eqO : O -> O -> Bool) (eqH : H -> H -> Bool) (eqS : S -> S -> Bool) (a : Closure O H S) (b : Closure O H S) =>',
          '  match a as self in Closure return Bool with']
for name, fields, result in ctors:
    lines.append(f'  | {name} ' + ' '.join(n for n, _ in fields) + ' => (match b as other in Closure return Bool with')
    for other, fields2, _ in ctors:
        lines.append(f'    | {other} ' + ' '.join(n+'2' for n, _ in fields2) + ' => ' + (result if name == other else 'false'))
    lines[-1] += ')'
(root / 'src/theory_core.kan').write_text('\n'.join(lines)+'\n')
